name: attendance

on:
  workflow_dispatch:
  schedule:
    # 日本時間 平日8:45
    # GitHub Actions は UTC
  - cron: '*/5 * * * *'

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install --with-deps

      - name: Run script
        env:
          USER_ID: ${{ secrets.USER_ID }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: python attendance.py
