name: attendance

on:
  schedule:
    # 日本時間 平日8:45
    # GitHub Actions は UTC なので 23:45 UTC = JST 8:45
    - cron: '*/5 * * * *'

  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install --with-deps

      - name: Run script
        env:
          ATTENDANCE_ID: ${{ secrets.ATTENDANCE_ID }}
          ATTENDANCE_PASSWORD: ${{ secrets.ATTENDANCE_PASSWORD }}
        run: python attendance.py
